### ISSUE TITLE
 plone.autoform.base Field move to non-existing: field name: IDublinCore.description, rule: {'target': '*', 'dir': 'before'}

### ISSUE THREAD

**Issue by zopyx** [plone/plone.autoform#33] opened 2018-02-16 10:05 UTC
We have this schema

```
class IRichdocument(model.Schema):
    """ Marker interfce and Dexterity Python Schema for Richdocument
    """

    fieldset('Teaser', fields=[
        'teaser_title', 
        'teaser_description', 
        'teaser_text', 
        'teaser_image', 
        'teaser_image_caption'])

    text = RichText(
        title=_(u'Text'),
        required=False
    )

    teaser_title = schema.TextLine(
        title=_(u'Teaser text'),
        required=False
    )
    teaser_description = schema.Text(
        title=_(u'Teaser description'),
        required=False
    )
    teaser_text = RichText(
        title=_(u'Teaser text'),
        required=False
    )
    teaser_image = NamedBlobImage(
        title=_(u'Teaser image'),
        required=False)
    teaser_image_caption = schema.TextLine(
        title=_(u'Teaser image caption'),
        required=False,
        )
```

which causes the following warning when we create resources in Plone 5.1 over plone.restapi.

2018-02-16 11:03:06 WARNING plone.autoform.base Field move to non-existing: field name: IDublinCore.description, rule: {'target': '*', 'dir': 'before'}
2018-02-16 11:03:06 WARNING plone.autoform.base Field move to non-existing: field name: IDublinCore.title, rule: {'target': '*', 'dir': 'before'}

**Comment by nazrulworld** [comment] 2018-02-16 10:16
Same here, I am also getting same warning.

**Comment by fgrcon** [comment] 2018-03-08 11:06
see: https://github.com/plone/plone.autoform/issues/21

**Comment by ale-rt** [comment] 2020-03-03 09:27
Closing this because it is a duplicate of #21.

**Closed by ale-rt** 2020-03-03 09:27 UTC
